kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-roboshop
provisioner: efs.csi.aws.com
reclaimPolicy: Retain 
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0fee86fbdff79f8ab
  directoryPerms: "700"
  basePath: "/roboshop" # /roboshop/cart